In [22]:
# load libraries
import pandas as pd
import numpy as np
import pyarrow.feather as feather
import seaborn as sns
from matplotlib import pyplot as plt   #plt.xkcd()
from IPython.display import set_matplotlib_formats
import matplotlib.ticker as mtick
import scipy.stats as ss
from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Improve quality of the plots
set_matplotlib_formats('svg')
# Set the style of the plot
plt.style.use('seaborn-v0_8-white')

In [30]:
# Load the data
df = pd.read_csv("data.csv", index_col=0)
df.reset_index(drop=True, inplace=True)
df.head(5)

,expo,nclaims,amount,coverage,ageph,sex,bm,power,agec,fuel,use,fleet,long,lat
0,0.073973,0,0.0,TPL,73,male,0,77,5,gasoline,private,0,5.500567,50.583188
1,0.265753,0,0.0,TPL+,33,female,7,50,5,diesel,private,0,3.982742,50.807099
2,1.000000,0,0.0,TPL,32,male,2,100,11,gasoline,private,0,4.193470,51.133515
3,1.000000,0,0.0,TPL+,47,male,5,96,2,gasoline,private,0,5.364856,50.992450
4,1.000000,0,0.0,TPL++,43,male,1,65,2,gasoline,private,0,4.387146,51.216042